
MBROKER_HOST: localhost 
MBROKER_PORT: 5672
MBROKER_USERNAME: guest
MBROKER_PSW: guest 



server:
    port: 8083
    servlet:
      context-path: /service-track


spring:
  profiles.active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/st
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  

seguranca:
   jwtSECRET: "SOL-VIOLAO-PRAIA"
   




 

